name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1  # v3.0.2
    with:
      envs: |
        - linux: py311-astropystable
        - linux: py311-astropydev
