name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a  # v3.0.3
    with:
      envs: |
        - linux: py311-astropystable
        - linux: py311-astropydev
