name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174  # v3.0.1
    with:
      envs: |
        - linux: py311-astropystable
        - linux: py311-astropydev
